### ISSUE TITLE
Need help: Error occurs when trying to build or start

### ISSUE THREAD

**Issue by VikasDayananda** [wrobin/favesound-redux#124]
I am working on windows. Build fails with below error. Any Insights?

ERROR in ./node_modules/css-loader!./node_modules/sass-loader!./styles/index.scss
Module build failed: Error: ENOENT: no such file or directory, scandir 'C:\Users\Desktop\open source\favesound-redux\node_modules\node-sass\vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (C:\Users\Desktop\open source\favesound-redux\node_modules\node-sass\lib\extensions.js:124:13)
    at foundBinariesList (C:\Users\Desktop\open source\favesound-redux\node_modules\node-sass\lib\errors.js:20:15)
    at foundBinaries (C:\Users\Desktop\open source\favesound-redux\node_modules\node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (C:\Users\Techmileage\Desktop\open source\favesound-redux\node_modules\node-sass\lib\errors.js:45:5)
    at module.exports (C:\Users\Desktop\open source\favesound-redux\node_modules\node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (C:\Users\Desktop\open source\favesound-redux\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
 @ ./styles/index.scss 4:14-112 18:2-22:4 19:20-118
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:8080 webpack/hot/only-dev-server ./src/index.js
webpack: Failed to compile.

**Comment by rwieruch** [comment]
Checkout this issue https://github.com/rwieruch/favesound-redux/issues/18 where the sass rebuild is mentioned. I hope it helps you to get started.

**Comment by VikasDayananda** [comment]
Thanks.Below comment fixed the issue-
https://github.com/rwieruch/favesound-redux/issues/18#issuecomment-280576453
